### PR TITLE
Added explanations to README

### PR DESCRIPTION
**Pull request by asahai**
I added an explanation for non or beginning level coders on how to customize the Rails-Retweeter-Bot for their own needs through editing keywords in the whitelist, blacklist, and changing the threshold values for which tweets get retweeted.

Regards,
Alex Sahai
@AlexSahai

### CODE REVIEW

**Comment by mackuba** [comment]
Thanks, merged.

I had a bit of a mindfuck trying to figure out if you and @AlexFine who sent #3 a week before are the same person or not... :) But it looks like you just work together, right? :)

Out of curiosity, what kind of bot are you making?

**Comment by mackuba** [comment]
FYI, I've done some more edits to the readme here: https://github.com/mackuba/rails-retweeter-bot/commit/40fd23efa286ca33560fcde7b59abc09d74eec1c

**Comment by asahai** [comment]
We are not the same person, but we are both students in the same CS class in high school. We contributed to the Rails bot as part of an Open-Source project for the class. We still had some trouble getting everything live on our own twitter accounts, so our contributions were documentation based. I’m going to see if I can get the project live on my twitter account, and I’ll update with you regarding my troubleshooting process.  

We wanted to make a retweeting bot for our startup Bay Area Student Entrepreneurs (@codingsf) to aggregate more followers and find interesting content. We wanted to see if we could implement a following tool by creating some sort of algorithm (like your user_awesomeness_threshold) that identifies people using certain hashtags and getting good engagement. Do you have any ideas on that?  

Thanks,
Alex Sahai
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by mackuba** [comment]
Nice :) As for automatically finding new people - hmm, that might be tricky. Not everyone uses hashtags, most people use them sparingly or not at all. Perhaps a good approach would be to scan the following lists of an initial set of people and then finding people who are followed by a large subset of that set. But you'll probably quickly run into Twitter's rate limits with that... You could also try enabling loading retweets  on the bot's timeline, then you can find new people by checking who is retweeted by the people you follow, and then follow those new people if they match some criteria.

**Pull request merged**
